# coding: utf-8
# Generated by setup.py for PyCBC on .

version = '2.0.1'
date = ''
release = True
last_release = ''

git_hash = ''
git_branch = ''
git_tag = ''
git_author = ''
git_committer = ''
git_status = ''
git_builder = ''
git_build_date = ''
git_verbose_msg = """Version: 2.0.1
Branch: 
Tag: 
Id: 
Builder: 
Build date: 
Repository status is """
from pycbc._version import *
